### ISSUE TITLE
C:\opt\rosdeps\x64\bin\cmake.exe: DOES NOT EXIST

### ISSUE THREAD

**Issue by KevinPatel04** [Brabalawuka/RosOnWindows#1]
Hey @Brabalawuka,
I have followed all the steps you have mentioned in the markdown file but my `C:\opt\rosdeps\x64\bin\` folder doesnot contain cmake.exe file. Even after uncommenting the line#136 (last 2nd step) the file type is miscellaneous file only so I am not able to run the hello world program.  

`C:\opt\rosdeps\x64\bin\cmake.exe' '--version' execution failed with error: 'Failed to start the process with command 'C:\opt\rosdeps\x64\bin\cmake.exe --version' (The system cannot find the file specified).'.
`

 What should I do?

![image](https://user-images.githubusercontent.com/42532908/86268566-004add80-bbe6-11ea-83c2-6deb1903f09e.png)
![image](https://user-images.githubusercontent.com/42532908/86268630-19ec2500-bbe6-11ea-9049-02abaee91f0c.png)
![image](https://user-images.githubusercontent.com/42532908/86268762-486a0000-bbe6-11ea-8aee-6622d99101ae.png)
![image](https://user-images.githubusercontent.com/42532908/86268900-8f57f580-bbe6-11ea-8673-5770d1a0b266.png)

**Comment by lyuzizheng** [comment]
Hi, this is quite an old repo and i am sorry it is not working. I believe any cmake will be ok in this case so i think u can try install ur own cmake and choose the directory. Let me know if this works as in I am not working on ROS anymore.

**Comment by KevinPatel04** [comment]
Thank you @Brabalawuka I figured it out.
